### PR TITLE
fixes documentation for rotate function

### PR DESCRIPTION
**Pull request by JoshMcCullough**
I observed that a positive value for `degrees` rotate CS, and a negative value rotates CCW.

### CODE REVIEW

**Comment by dlemstra** [comment]
Thanks for fixing this 👍. I also had to update the Magick++ documentation where I copied this from.

**Comment by JoshMcCullough** [comment]
Hopefully I was correct. This is what I observed...

**Comment by dlemstra** [comment]
Your observation is correct 🥇. And the usage documentation also states this: http://www.imagemagick.org/Usage/warping/#rotate. I just copied the text from Magick++ without reading what it said.

**Comment by JoshMcCullough** [comment]
Okay, great!

**Pull request merged**
