### PR TITLE
fix linker order for freetype/fontconfig

### PR DESCRIPTION
**Pull request by superstator**
It was just the linker order - the libraries in AdditionalDependencies have to be in the same order, more or less, as the Docker build

### CODE REVIEW

**Comment by dlemstra** [comment]
Never knew link order could be an issue, thanks for the fix. Could you also take a look at the .dockerignore files? Not sure if they are still correct.

**Comment by superstator** [comment]
Sure thing. I noticed you checked authorized_keys back in with your public in it - was that intentional, or would you like me to clean that up too while I'm at it?

**Comment by dlemstra** [comment]
Yup I re-added the authorized_keys because that was easier for me :)

**Comment by superstator** [comment]
Ok. I cleaned up the ignore files, it pruned 4-500mb from the build context for me at least. Should be ready to merge if it looks good to you.

**Comment by dlemstra** [comment]
Waiting with this PR until I rebuild ImageMagick again. Looks fine to me. Thanks for helping me out

**Comment by dlemstra** [comment]
Works perfectly thanks for the PR 👍

**Pull request merged**
