### PR TITLE
add ToBitmap() methods to netstandard2.0 version

### PR DESCRIPTION
**Pull request by halex2005**
[System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common) package provides access to GDI+ graphics functionality cross-platform.
We can use it in .NET Core applications targeting to netstandard2.0.

https://www.hanselman.com/blog/HowDoYouUseSystemDrawingInNETCore.aspx

### CODE REVIEW

**Comment by halex2005** [comment]
I don't touch any test, I just enable some parts of code in netstandard2.0 using preprocessor definitions. Single test failed - `ShouldMergeTheImages` like here in master (master builds also failed): https://github.com/dlemstra/Magick.NET/runs/492619989?check_suite_focus=true

Can anyone help me to fix that test? If it is necessary to get green build for this PR...

**Comment by dlemstra** [comment]
The current master is broken due to some unexpected changes inside ImageMagick and I am working on a fix. 

Thanks for your contribution but I don't want to add a dependency to the `System.Drawing.Common` library in this project. As you can see it Scott his post this also requires some extra dependencies to be installed to make this work. And he also states the following:

> It's important to understand that this System.Drawing layer is great for existing System.Drawing code, but you probably shouldn't write NEW image management code with it.

The reason that `System.Drawing` is used in this library is to make it possible to use this library in code that still uses the `System.Drawing` library. But that is only for projects that still use .NET Framework. I hope this explains why I don't want to merge your pull request.

**Comment by halex2005** [comment]
Thanks for reply.
Let me try to reflect why this PR could be helpful.

1) `System.Drawing.Common` has no extra .nuget dependencies for netstandard2.0 and should work cross-platform.

2) Yes, on Ubuntu it may require to install the dependencies:
    ```
    sudo apt install libc6-dev 
    sudo apt install libgdiplus
    ```
    But Magick.NET already has extra requirements for [cross-platform running](https://github.com/dlemstra/Magick.NET/blob/master/docs/CrossPlatform.md). We may add it to documentation and build scripts.

3)
   > this System.Drawing layer is great for existing System.Drawing code, but you probably shouldn't write NEW image management code with it

   I agreed. But Magick.NET is not NEW image mangement code :) Your code is already written and proven. There may be an old code (like I have) that uses your library code's `IMagickImage.ToBitmap` method. If you support that scenario, migration of old code base to modern frameworks will be smooth and easier.

BTW, you is maintainer, you'll decide.

If you don't want to add a dependency to the System.Drawing.Common library in this project, feel free to close this PR.

Thanks for great library!

**Comment by dlemstra** [comment]
To be clear the Linux version of the library has no extra install dependencies. It works without installing anything extra. Thanks for your contribution but I will not include a dependency on `System.Drawing.Common` in this project.

**Pull request closed without merging**
