### PR TITLE
Replace vague instructions for Mono with precise ones

### PR DESCRIPTION
**Pull request by YoshiRulz**
### Description
Updates the section for Mono (.NET Framework on Linux) in the documentation for "cross-platform" users. Though I'm grateful it works at all, I thought since I've put in the effort to get a working and *clean* build config I'd offer it for others to copy. I apologise for not automating the host RID part; I only use Linux.

### CODE REVIEW

**Comment by dlemstra** [comment]
Thanks for pointing this out and this should be updated. But you should also be able to achieve this by doing this in your `.csproj`: 
```xml
<PropertyGroup>
  <MagickCopyNativeLinux>true</MagickCopyNativeLinux>
</PropertyGroup>
```

This was "recently" added and is not yet documented.

**Comment by YoshiRulz** [comment]
That is documented immediately above the Mono section. But it doesn't work, which I'm guessing is because the filename is wrong.

**Comment by dlemstra** [comment]
Whoops... I thought I did not document that yet but it turns out I did. It would be nicer if we could fix this on Mono by patching the `Magick.NET.targets` file in the `publish` folder. Maybe we could add and extra property `MagickCopyNativeMono` that adds `lib` between `%(FileName)` and `%(Extension)` when that property is true?

**Comment by YoshiRulz** [comment]
I don't know how to test a patched version of a NuGet package.

But if you're willing to change it, was there a reason the filenames were `.dll.so` for .NET Core in the first place? I thought only Mono used that convention.

**Comment by dlemstra** [comment]
You will need to edit that file in your NuGet cache to test this locally. You can find the folders with `dotnet nuget locals all -l`. You can then find that `.targets` file in the folder of this package.

I think I had to add the `.dll.so` to get `DllImport` to work. But that was ages ago when the first version of .NET Core was launched. And I have seen people requiring to add `lib` before the name but I never figured out what was the cause of that. It doesn't seem to be required otherwise everyone that runs this library on linux would need to do this manual step.

**Comment by YoshiRulz** [comment]
This works:
```diff
-  <ItemGroup Condition="'$(MagickCopyNativeLinux)' == 'true'">
+  <ItemGroup Condition="'$(MagickCopyNativeLinux)' == 'true' OR '$(MagickCopyNativeLinuxForMono)' == 'true'">
     <NativeLinuxDLL Include="$(MSBuildThisFileDirectory)\..\..\runtimes\linux-x64\native\*.so" />
     <None Include="@(NativeLinuxDLL)">
       <Link>%(FileName)%(Extension)</Link>
+      <Link Condition="'$(MagickCopyNativeLinuxForMono)' == 'true'">lib%(FileName)%(Extension)</Link>
       <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
     </None>
```
As does this:
```diff
+  <ItemGroup Condition="'$(MagickCopyNativeMono)' == 'true'">
+    <NativeLinuxDLL Include="$(MSBuildThisFileDirectory)\..\..\runtimes\linux-x64\native\*.so" />
+    <None Include="@(NativeLinuxDLL)">
+      <Link>lib%(FileName)%(Extension)</Link>
+      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
+    </None>
+  </ItemGroup>
```

**Comment by dlemstra** [comment]
I wonder if we could improve the detection and add the `lib` automatically:

```xml
  <ItemGroup Condition="('$(TargetFrameworkIdentifier)' == '.NETFramework' AND '$(MagickCopyNativeWindows)' != 'false') OR '$(MagickCopyNativeWindows)' == 'true'">
    <NativeWindowsDLL Include="$(MSBuildThisFileDirectory)\..\..\runtimes\win*\native\*.dll" />
    <None Include="@(NativeWindowsDLL)" Condition="'$(GenerateManifests)' != 'true'">
      <Link>%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Content Include="@(NativeWindowsDLL)" Condition="'$(GenerateManifests)' == 'true'">
      <Link>%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup Condition="'$(MagickCopyNativeLinux)' == 'true'">
    <NativeLinuxDLL Include="$(MSBuildThisFileDirectory)\..\..\runtimes\linux-x64\native\*.so" />
    <None Include="@(NativeLinuxDLL)">
      <Link Condition="'$(TargetFrameworkIdentifier)' != '.NETFramework'">%(FileName)%(Extension)"</Link>
      <Link Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">lib%(FileName)%(Extension)"</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <NativeLinuxArm64DLL Include="$(MSBuildThisFileDirectory)\..\..\runtimes\linux-arm64\native\*.so" />
    <None Include="@(NativeLinuxArm64DLL)">
      <Link>%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

Would this work for you with the following settings:

```
<PropertyGroup>
  <MagickCopyNativeWindows>false</MagickCopyNativeWindows>
  <MagickCopyNativeLinux>true</MagickCopyNativeLinux>
</PropertyGroup>
```

This should prevent copying of the windows libraries and only using the `.so` files.

**Comment by YoshiRulz** [comment]
After removing the stray quotes in the `<Link/>` values, that change also works.

**Comment by dlemstra** [comment]
Thanks for helping out and testing this with me. I will be going to use the latest idea and update the documentation.

**Comment by dlemstra** [comment]
I just pushed a commit that addresses the changes that I proposed in this pull request and that will come available in the next release. Closing this now.

**Comment by YoshiRulz** [comment]
Confirmed new method in 13.9.0 works great with Mono.

**Comment by dlemstra** [comment]
Thanks for coming back and telling me that

**Pull request closed without merging**
